cam0:
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: equidistant
  intrinsics: [400, 400, 400, 200]
  resolution: [800, 400]
  rostopic: vio1_front/camera
