mrs_uav_flightforge_simulator:

  realtime_factor: 1.0 # [-]

  #  0 - LOW
  #  1 - MEDIUM
  #  2 - HIGH
  #  4 - EPIC
  #  5 - CINEMATIC
  graphics_settings: "low"

  # 0 -  VALLEY
  # 1 -  FOREST (only in the full version)
  # 2 -  INFINITE_FOREST (only in the full version)
  # 3 -  WAREHOUSE
  # 4 -  CAVE
  # 5 -  ERDING_AIRBASE (only in the full version)
  # 6 -  TEMESVAR (only in the full version)
  world_name: "forest"

  #  {"sunny", 0},
  #  {"cloudy", 1},
  #  {"foggy", 2},
  #  {"rain", 3},
  #  {"rain_light", 4},
  #  {"rain_thunderstorm", 5},
  #  {"sand_dust_calm", 6},
  #  {"sand_dust_storm", 7},
  #  {"snow", 8},
  #  {"snow_blizzards", 9}
  weather_type: "cloudy"

  daytime:
    hour: 12
    minute: 25

  ############ Only Forest Procedural Generation settings ############

  # Choose cluttered difficulties from 1 [high] to 10 [low]
  ueds_forest_density: 6

  # Choose Hilly Level from 1 [totally flat] to 5 [the most hilly]
  ueds_forest_hilly_level: 3

  ####################################################################

  sensors:

    rangefinder:

      enabled: true
      rate: 10.0 # [Hz]

    lidar:

      enabled: false

    rgb:

      enabled: true

      rate: 30.0 # [Hz]

      enable_hdr: true
      enable_temporal_aa: true
      enable_raytracing: true

      width: 640 # [px]
      height: 480 # [px]
      fov: 120.0 # [deg]

      offset:
        x: 0.14 # [m]
        y: 0.0 # [m]
        z: 0.0 # [m]

      # TODO which Tait-Bryan convention is it in?
      rotation:
        pitch: 0.0 # [deg]
        yaw: 0.0 # [deg]
        roll: 0.0 # [deg]

      enable_motion_blur: true
      motion_blur_amount: 0.5 # [0.0 - 1.0]
      motion_blur_distortion: 50.0 # [0-100]

      rgb_segmented:
        enabled: false
        rate: 5.0 # [Hz]

      depth:
        enabled: false
        rate: 10.0 # [Hz]

    stereo:

      enabled: false

# * when enabled, this will place a temporary patch of ground just under the spawn location
# * this patch will disappear after the total_thrust > 0.9*hover_thrust
individual_takeoff_platform:
  enabled: false
